# Site settings
title: Shuyuan Lin
url: "http://www.linshuyuan.com" 
baseurl: "" 
baidu-analysis: a2b397dbd7421f79a8936cb9c2b93691
#timezone: Asia/Chongqing
description: >
   My personal website.

# Your information
email: swin.shuyuan.lin@gmail.com
author: Shuyuan Lin
avatar: "//www.gravatar.com/avatar/your_email_md5?d=mm&s=135"
profile: ...
#twitter_username: twitter_username
#github_username:  github_username

profile_links:
  Email: "mailto:swin.shuyuan.lin@gmail.com"

  URL: "http://www.linshuyuan.com"
  # You can add more profile links above, or edit _includes/sidebar.html 

# Comment Service
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

excerpt_separator: <!--more-->

header:
  links:             # Links on the header. Link to in-site page with a slash as prefix
    About: /about/
    Publications: /publications/
    Category: /category/


permalink: /archivers/:title
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji


# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

# https://jekyllrb.com/docs/configuration/#precedence
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax

